services:
  web:
    image: DOCKERHUB_USERNAME/devop-midterm-web:1.0.0
    container_name: devop_midterm_web
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - uploads_data:/app/public/uploads
      - logs_data:/app/logs
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: devop_midterm_mongo
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
  uploads_data:
  logs_data: